name: Run tests

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - \d+.\d+.\d+

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup bitrise
        run: |
          uname -s
          https://github.com/bitrise-io/bitrise/releases/2.16.1/download/bitrise-$(uname -s)-$(uname -m)
          curl -fL https://github.com/bitrise-io/bitrise/releases/2.16.1/download/bitrise-$(uname -s)-$(uname -m) > /usr/local/bin/bitrise
          chmod +x /usr/local/bin/bitrise
          bitrise setup
      - name: Prepare secrets 
        run: ruby -rerb -e 'File.write(".bitrise.secrets.yml", ERB.new(File.read(ARGV[0])).result(binding))' .bitrise.secrets.yml.erb
      - name: Run tests
        run: bitrise run test
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_APP_KEY: ${{ secrets.TEST_APP_KEY }}
